name: Konstruct Website
markdown: redcarpet
highlighter: null
baseurl: "/Konstruct"
url: http://localhost:4000
version: 1
permalink: /:categories/:title
exclude: [README.md, ROADMAP.md, Gruntfile.js, package.json, 'node_modules', 'TRM - traaidmark.com.esproj']