name: Konstruct Website
markdown: redcarpet
pygments: false
url: /
version: 1
permalink: /:categories/:title
exclude: [README.md, ROADMAP.md, Gruntfile.js, package.json, 'node_modules', 'TRM - traaidmark.com.esproj']